---
  mcu: "stm32f401cc"
  extClockMhz: 25
  usb: true
  uart:
    dinMIDI:
      channel: 1
    touchscreen:
      channel: 0
      components: 64
  i2c:
    display:
      channel: 0
  analog:
    type: "4067"
    multiplexers: 4
    inputVoltage: "3.3"
    pins:
      s0:
        port: "B"
        index: 1
      s1:
        port: "B"
        index: 0
      s2:
        port: "B"
        index: 2
      s3:
        port: "B"
        index: 10
      z0:
        port: "A"
        index: 4
      z1:
        port: "A"
        index: 5
      z2:
        port: "A"
        index: 6
      z3:
        port: "A"
        index: 7
    indexing:
    - 15
    - 14
    - 13
    - 12
    - 11
    - 10
    - 9
    - 8
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 31
    - 30
    - 29
    - 28
    - 27
    - 26
    - 25
    - 24
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
    - 23
    - 47
    - 46
    - 45
    - 44
    - 43
    - 42
    - 41
    - 40
    - 32
    - 33
    - 34
    - 35
    - 36
    - 37
    - 38
    - 39
    - 63
    - 62
    - 61
    - 60
    - 59
    - 58
    - 57
    - 56
    - 48
    - 49
    - 50
    - 51
    - 52
    - 53
    - 54
    - 55
